#!/bin/bash
set -eu

SSHPATH="$HOME/.ssh"
mkdir -p "$SSHPATH"
echo "$DEPLOY_KEY" > "$SSHPATH/key"
chmod 600 "$SSHPATH/key"
SERVER_DEPLOY_STRING="$USERNAME@$SERVER_IP:$SERVER_DESTINATION"
# sync it up"
sh -c "rsync $ARGS -e 'ssh -i $SSHPATH/key -o StrictHostKeyChecking=no -p $PROXY_SERVER_PORT -A $PROXY_SERVER_USERNAME@$PROXY_SERVER_IP ssh' $SERVER_DEPLOY_STRING $GITHUB_WORKSPACE/$FOLDER"
